# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e3838eae9d8f4d520127ce676a9c2d60"
name = "sections-stack"
handle = "sections-stack"
application_url = "https://convicted-jun-cooler-cg.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_themes"


[auth]
redirect_urls = ["https://convicted-jun-cooler-cg.trycloudflare.com/auth/callback", "https://convicted-jun-cooler-cg.trycloudflare.com/auth/shopify/callback", "https://convicted-jun-cooler-cg.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
